# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../00_core.ipynb 2
def say_hello(to: str):
    "Say Hello to somebody"
    return f"Hello {to}!"

# %% ../00_core.ipynb 6
def foo(dog: str)->int: 
    """
    """
    print(dog +"says, 'fipple-fop'")
